# Generated by Django 5.2.8 on 2025-12-09 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(blank=True, max_length=150)),
                ('origem', models.CharField(blank=True, max_length=100)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('estado_conservacao', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria')),
            ],
        ),
    ]
