# Generated by Django 5.2.8 on 2025-12-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pecas/'),
        ),
    ]
