# Generated by Django 5.2.8 on 2025-12-09 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('contato', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=1)),
                ('tipo', models.CharField(choices=[('IND', 'Individual'), ('GRP', 'Grupo/Escola')], default='IND', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateTimeField()),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitantes.visitante')),
            ],
        ),
    ]
